=== CQzhangshuai/htte/packages/htte-schema-validator/src/config.schema.json
{
  "$id": "http://example.com/config.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "session": {
      "type": "string"
    },
    "modules": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "clients": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "pkg": {
            "type": "string"
          },
          "options": {
            "type": "object"
          }
        },
        "required": ["name", "pkg"]
      }
    },
    "reporters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "pkg": {
            "type": "string"
          },
          "options": {
            "type": "object"
          }
        },
        "required": ["name", "pkg"]
      }
    },
    "plugins": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "pkg": {
            "type": "string"
          },
          "options": {
            "type": "object"
          }
        },
        "required": ["pkg"]
      }
    },
    "defines": {
      "$ref": "defines.json"
    }
  },
  "required": ["modules"]
}

=== CQzhangshuai/htte/packages/htte-schema-validator/src/__tests__/fixtures/config.json
{
    "session": "mysession.json",
    "modules": [
        "auth",
        "article"
    ],
    "reporters": [
        {
            "name": "cli",
            "pkg": "htte-reporter-cli",
            "options": {
                "slow": 500
            }
        }
    ],
    "clients": [
        {
            "name": "http",
            "pkg": "htte-client-http"
        },
        {
            "name": "grpc",
            "pkg": "htte-client-grpc",
            "options": {
                "proto": "myproto.proto"
            }
        }
    ],
    "plugins": [
        {
            "pkg": "htte-plugin-builtin"
        }
    ],
	"defines": {
		"login": {
			"client": "http",
			"req": {
				"method": "post",
				"uri": "/login"
			}
		},
		"auth": {
			"client": "grpc",
			"req": {
				"method": "auth"
			}
		}
	}
}
